### ISSUE TITLE
效果如何，怎么一个提问都没有呢

### ISSUE THREAD

**Issue by xxm1668** [wenge-research/YaYi#1]

**Comment by wenge-research** [comment]
如果模型训练/推理遇到任何问题，欢迎提出&交流~

**Comment by xxm1668** [comment]
有与其他模型对比效果实验吗？

**Comment by xxm1668** [comment]
推理速度贼慢，500条数据，推理差不多3个小时。。。弃了

**Comment by vflyvv** [comment]
> 推理速度贼慢，500条数据，推理差不多3个小时。。。弃了

你是什么卡？可能有配置问题。

**Comment by xunan0812** [comment]
> 推理速度贼慢，500条数据，推理差不多3个小时。。。弃了

A100-nvlink单卡很快啊，再使用vllm的话还能加速
