### ISSUE TITLE
可以提供更详细一些的信息吗？

### ISSUE THREAD

**Issue by nuoma** [wenge-research/YaYi#3]
你好，关于你们的模型[yayi-13b-llama2](https://huggingface.co/wenge-research/yayi-13b-llama2)，希望能够提供更多的信息。比如我现在能看到词表32005是没有动过的。你们的增量中文预训练数据大约是什么样的量级？有没有拿他跑过类似ceval和cmmlu这类的分数？谢谢！

**Comment by huxiaosheng123** [comment]
可以参考：https://github.com/huxiaosheng123/open-llama2

**Comment by wenge-research** [comment]
开源版本我们扩展了用于Chat的special token；Ceval 当时9月份打过榜，如图：
![image](https://github.com/wenge-research/YaYi/assets/133115410/e80270c7-d92a-4bdd-b2b0-99fed73ff3f0)

mmlu等其他榜单我们提交了huggingface open_llm_leaderboard。
