### ISSUE TITLE
关于C-Eval的测评

### ISSUE THREAD

**Issue by FangGet** [wenge-research/YaYi#4]
您好，感谢您开源YaYi相关模型，我想问一下您在C-Eval榜单上的模型，是您开源的版本么？如果是其他版本，能稍微给些大致信息么？因为我用您开源的YaYi-13B-LLaMa2的模型在C-Eval的测试集测评，效果和榜单差距过大。

**Comment by wenge-research** [comment]
C-Eval 榜单上的 YaYi 使用的内部正在研发的更大参数量、采用更多数据训练的模型~

**Comment by FangGet** [comment]
明白，多谢
