### ISSUE TITLE
网页端[新闻主题分类/主题分类]功能无法使用，无论发什么内容*（包括内置示例）都是涉政不让问

### ISSUE THREAD

**Issue by songkq** [wenge-research/YaYi#5]
@wenge-research 请教下正确食用方法
![image](https://github.com/wenge-research/YaYi/assets/30183023/0497f6c7-a647-4a7c-97e6-0fd6aefb8095)

**Comment by Lucinao540** [comment]
多轮对话导致的，后面会开启新对话。这个问题即可解决

**Comment by songkq** [comment]
@Lucinao540 好的，请问预计多久以后可以正常使用这个功能

**Comment by songkq** [comment]
@Lucinao540 @wenge-research 请问网页端体验的模型就是开源的YaYi-13B-Llama2版本吗？

YaYi-13B-Llama2 | wenge-research/yayi-13b-llama2
-- | --

**Comment by wenge-research** [comment]
网页端是内部不断迭代的模型版本，我们也对安全接口也做了升级优化，体验会好很多。
