### ISSUE TITLE
开源模型训练方式

### ISSUE THREAD

**Issue by yangjianxin1** [wenge-research/YaYi#6]
请问yayi开源的模型，是使用全量参数训练，还是使用lora训练的？使用了多少训练资源？期待您的回答。

**Comment by ZouRuia** [comment]
据我了解，全量的

**Comment by yangjianxin1** [comment]
> 据我了解，全量的

感谢解答~

**Comment by wenge-research** [comment]
您好，是全参数微调的，训练资源使用 N*8*80G A100，各阶段的 N 取决于 sft 数据量、batch size 和对训练时间的安排。
